server:
  port: 8080
spring:
  application:
    name: "advertising"
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/advertising?currentSchema=public
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
    logging:
      level:
        org.springframework.web: DEBUGrec
  jpa:
    #properties:
    #hibernate:
    #dialect: "com.test.CustomPostgreSQLDialect"
    hibernate:
      ddl-auto: none # When you launch the application for the first time - switch "none" at "create"
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    database: postgresql
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
db:
  manangment:
    url: jdbc:postgresql://localhost:5432/public
    host: localhost
    bdname: advertising
    port: 5432
    username: postgres
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  pathsToMath: /agency/api/v1/**
  packagesToScan: co.com.agency
  api-docs:
    path: /agency/api/v1/api-docs
