FROM adoptopenjdk/openjdk8-openj9
VOLUME /tmp
COPY *.jar advertising.jar
ENV JAVA_OPTS=" -Xshareclasses:name=cacheapp,cacheDir=/cache,nonfatal -XX:+UseContainerSupport -XX:MaxRAMPercentage=70 -Djava.security.egd=file:/dev/./urandom"
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS  -jar advertising.jar" ]
EXPOSE 8080
